In [1]:
import pandas as pd

In [2]:
team_df = pd.read_csv('./raw_data/raw/team_traditional.csv', sep=",")

In [3]:
team_df

,gameid,date,type,teamid,team,home,away,MIN,PTS,FGM,...,DREB,REB,AST,TOV,STL,BLK,PF,+/-,win,season
0,29600001,1996-11-01,regular,1610612738,BOS,BOS,CHI,240.0,98.0,38.0,...,22.0,36.0,20.0,18.0,10.0,2.0,33.0,-45.0,0.0,1997
1,29600001,1996-11-01,regular,1610612741,CHI,BOS,CHI,240.0,107.0,42.0,...,29.0,37.0,28.0,19.0,7.0,8.0,23.0,45.0,1.0,1997
2,29600002,1996-11-01,regular,1610612739,CLE,NJN,CLE,238.0,90.0,34.0,...,23.0,35.0,16.0,15.0,11.0,1.0,24.0,65.0,1.0,1997
3,29600002,1996-11-01,regular,1610612751,NJN,NJN,CLE,241.0,77.0,23.0,...,24.0,35.0,13.0,21.0,7.0,7.0,19.0,-65.0,0.0,1997
4,29600003,1996-11-01,regular,1610612749,MIL,PHI,MIL,240.0,111.0,38.0,...,31.0,50.0,21.0,14.0,9.0,7.0,30.0,40.0,1.0,1997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65569,52200131,2023-04-12,playin,1610612740,NOP,NOP,OKC,48.0,118.0,42.0,...,34.0,48.0,27.0,11.0,5.0,4.0,23.0,-5.0,0.0,2023
65570,52200211,2023-04-14,playin,1610612750,MIN,MIN,OKC,48.0,120.0,43.0,...,38.0,47.0,29.0,17.0,11.0,8.0,15.0,25.0,1.0,2023
65571,52200201,2023-04-14,playin,1610612748,MIA,MIA,CHI,48.0,102.0,32.0,...,41.0,51.0,19.0,13.0,7.0,2.0,20.0,11.0,1.0,2023
65572,52200201,2023-04-14,playin,1610612741,CHI,MIA,CHI,48.0,91.0,36.0,...,32.0,37.0,24.0,11.0,5.0,3.0,25.0,-11.0,0.0,2023
65573,52200211,2023-04-14,playin,1610612760,OKC,MIN,OKC,48.0,95.0,32.0,...,30.0,42.0,19.0,18.0,9.0,6.0,20.0,-25.0,0.0,2023

In [3]:
game_ids = team_df['gameid'].unique()

In [5]:
len(game_ids)

32787

In [ ]:
df = pd.DataFrame()

In [15]:
df_iter = pd.read_csv('./raw_data/reduced/play_by_play01.csv', sep=',')

In [11]:
df = next(df_iter)

In [12]:
df5 = df[df['score'].notnull()]

In [17]:
df_iter['score']

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
           ...
999995    36 - 36
999996        NaN
999997        NaN
999998        NaN
999999        NaN
Name: score, Length: 1000000, dtype: object

In [7]:
iter_num = 1

while True:
    try:
        df0 = next(df_iter)
        df0 = df0[df0['score'].notnull()]
        df0 = df0[df0['game_id'].isin(game_ids)]
        
        df0.to_csv(f'./raw_data/play_by_play{iter_num:02d}.csv', index=False)

        print(f'{len(df0)} valid rows saved to csv')
        
        iter_num = iter_num + 1
         
    except StopIteration:
            print("Finished loading data")
            break

1000000 valid rows saved to csv
999502 valid rows saved to csv
779239 valid rows saved to csv
713352 valid rows saved to csv
998349 valid rows saved to csv
997972 valid rows saved to csv
999498 valid rows saved to csv
997349 valid rows saved to csv
926234 valid rows saved to csv
922311 valid rows saved to csv

/home/asmabdulgafor/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

922129 valid rows saved to csv
998361 valid rows saved to csv
947183 valid rows saved to csv
558156 valid rows saved to csv
Finished loading data

In [18]:

# Testing if I get all the valid game ids because i forgot to above lol

pbp_game_id = []

for i in range(1,15):
    df1 = pd.read_csv(f'./raw_data/play_by_play{i:02d}.csv', sep=",")
    ids = df1['game_id'].unique()
    
    pbp_game_id.extend(ids)

In [20]:
pbp_game_id_unique = list(set(pbp_game_id))

In [21]:
len(pbp_game_id_unique)

28021

In [23]:
missing = set(game_ids)-set(pbp_game_id_unique)

In [24]:
missing

{29900800,
 21200896,
 21200897,
 22200323,
 21200898,
 22200325,
 21200899,
 21200900,
 21200901,
 21200902,
 21200903,
 29900811,
 21200904,
 21200905,
 21200906,
 21200907,
 21200908,
 29900817,
 21700625,
 21200909,
 42000404,
 21700629,
 21200910,
 29900823,
 21700632,
 21200912,
 21200913,
 29900827,
 22200347,
 21200916,
 22200350,
 21200918,
 21200919,
 21200920,
 29900834,
 21200922,
 21200923,
 21200924,
 21200925,
 21200926,
 21200927,
 21700649,
 21200929,
 29900843,
 21700652,
 22200365,
 22200366,
 21200934,
 21200935,
 21700657,
 21700658,
 21200938,
 21200939,
 21200940,
 21200941,
 21200942,
 21700664,
 21200944,
 21200945,
 21200946,
 21200947,
 21200930,
 22200382,
 22200383,
 21200951,
 21200952,
 21200953,
 29900867,
 29900868,
 22200389,
 29900870,
 21200958,
 21200959,
 21200960,
 22200394,
 21200962,
 21200963,
 21200964,
 21200965,
 21700687,
 21200967,
 21700689,
 29900882,
 21200970,
 29900884,
 21200972,
 21200931,
 21200974,
 21200975,
 21200976,
 21200977,
 21200978,
 21200979,
 21200980,
 21200981,
 21700703,
 21200983,
 21200984,
 21200985,
 21200986,
 21200987,
 21200988,
 29900902,
 21200990,
 21200991,
 21200992,
 21200993,
 29900907,
 21700715,
 21200996,
 21200997,
 21200932,
 21200999,
 21201000,
 21201001,
 21201002,
 21201003,
 29900917,
 21700726,
 29900919,
 29900920,
 21201008,
 21201009,
 21201010,
 21201011,
 21201012,
 29900926,
 21201014,
 21201015,
 22200449,
 29900930,
 21201018,
 29900932,
 21201020,
 21201021,
 21201022,
 21200933,
 22200457,
 21201025,
 21201026,
 29900940,
 21201028,
 21201029,
 21201030,
 21201031,
 29900945,
 21201033,
 22200467,
 22200468,
 29900949,
 21700755,
 21201038,
 21201039,
 22200473,
 21201041,
 21201042,
 21201043,
 21201044,
 21201045,
 29900959,
 21201047,
 29900961,
 21201049,
 21201050,
 21201051,
 21201052,
 21201053,
 29900967,
 29900968,
 21201056,
 21201057,
 21201058,
 21201059,
 21201060,
 22200494,
 21201062,
 21201063,
 21201064,
 21201065,
 21201066,
 29900980,
 21201068,
 21201069,
 21201070,
 21201071,
 21700793,
 21700794,
 21201074,
 22200508,
 29900989,
 21201077,
 21201078,
 21201079,
 22200513,
 21201081,
 21201082,
 21201083,
 29900997,
 21201085,
 21201086,
 21700808,
 21201088,
 21201089,
 21201090,
 22200524,
 21201092,
 21700814,
 21201094,
 22200528,
 21201096,
 21201097,
 22200531,
 21700820,
 21200936,
 21201101,
 21201102,
 29901016,
 21201104,
 21201105,
 21201106,
 21201107,
 21201108,
 21700830,
 29901023,
 21700831,
 29901025,
 21201113,
 21201114,
 22200548,
 21201116,
 21201117,
 21201118,
 21201119,
 21201120,
 22200554,
 22200555,
 21200937,
 29901037,
 21201125,
 22200559,
 22200560,
 21201128,
 21201129,
 21700851,
 21201131,
 21201132,
 21201133,
 29901047,
 21201135,
 21201136,
 29901050,
 29901051,
 21201139,
 21201140,
 29901054,
 21700863,
 21201143,
 21201144,
 21201145,
 21201146,
 21201147,
 21201148,
 21201149,
 21201150,
 29901064,
 21700873,
 21201151,
 29901067,
 22200588,
 21201152,
 21201153,
 21201158,
 29901072,
 21700880,
 21201161,
 21201154,
 29901076,
 21201164,
 22200598,
 21201166,
 21201155,
 21201168,
 29901082,
 21201170,
 21201171,
 21201156,
 21201173,
 21201174,
 21700896,
 21201176,
 21201157,
 21201178,
 21201179,
 21201180,
 21201181,
 21201182,
 21201183,
 21201184,
 21201185,
 29901099,
 21201159,
 21201188,
 21201189,
 29901103,
 22200623,
 22200624,
 21700911,
 21201160,
 22200628,
 21201196,
 21201197,
 21201198,
 21700920,
 21201200,
 21201201,
 21201162,
 21201203,
 21201204,
 21201205,
 21201206,
 21201163,
 21201208,
 22200642,
 22200643,
 21700932,
 21201212,
 21201213,
 22200647,
 21201215,
 21201216,
 21201165,
 21201218,
 22200652,
 21201220,
 21201221,
 21201222,
 21201223,
 21201224,
 21201225,
 21201226,
 22200660,
 21700948,
 21201167,
 21201230,
 20300115,
 22200666,
 20300122,
 22200670,
 21201169,
 21700961,
 22200675,
 29901158,
 40100201,
 40100202,
 40100203,
 40100204,
 21201172,
 40100205,
 21700975,
 21700976,
 29901169,
 22200690,
 40100211,
 40100212,
 40100213,
 40100214,
 22200695,
 40100215,
 29901177,
 21700988,
 29901181,
 22200701,
 21700990,
 21201175,
 40100221,
 21200943,
 40100222,
 40100223,
 29901189,
 21201177,
 40100224,
 40100225,
 20300169,
 40100231,
 21701003,
 22200716,
 40100232,
 20300174,
 40100233,
 40100234,
 21701009,
 40100235,
 21701011,
 22200731,
 21701021,
 21701022,
 20300189,
 20300194,
 21701031,
 20300199,
 22200746,
 20300203,
 22200749,
 20300209,
 20300211,
 21201186,
 22200759,
 21701048,
 22200761,
 21201187,
 21701054,
 20300223,
 21701057,
 20300225,
 20300227,
 21201190,
 21201191,
 40100301,
 40100302,
 40100303,
 40100304,
 21201192,
 40100305,
 40100306,
 21201193,
 40100311,
 22200793,
 40100312,
 40100313,
 21201194,
 40100314,
 20300254,
 40100315,
 40100316,
 21201195,
 40100317,
 22200805,
 21701094,
 22200809,
 20300271,
 21201199,
 20300280,
 20300286,
 21701119,
 21200948,
 21201202,
 20800008,
 20800009,
 20800012,
 20300300,
 22200846,
 22200847,
 20300303,
 22200852,
 21701143,
 21200949,
 20300316,
 21201207,
 20800030,
 20800031,
 20701104,
 22200870,
 20800038,
 21201209,
 40600103,
 21701162,
 20300331,
 21201210,
 20300336,
 21701169,
 21200950,
 21201211,
 40100401,
 20300341,
 20800054,
 40100402,
 22200888,
 40100403,
 40100404,
 21701182,
 20800065,
 22200900,
 20300357,
 20800070,
 20800072,
 21701195,
 20800078,
 40600142,
 21201217,
 22200914,
 20300370,
 22200919,
 22200922,
 21201219,
 20800092,
 40600164,
 20300393,
 22200938,
 22200939,
 20300399,
 20300402,
 20300408,
 22200958,
 21201227,
 20300421,
 20800135,
 22200968,
 22200969,
 21201228,
 40600203,
 21201229,
 20300426,
 20300427,
 20800146,
 40600213,
 40600216,
 20300440,
 22200987,
 20300446,
 20300447,
 52200101,
 20300453,
 21200955,
 52200111,
 22201007,
 20800177,
 22201016,
 52200121,
 20800186,
 20800189,
 22201024,
 22201025,
 52200131,
 21200956,
 20300489,
 20300490,
 22201035,
 20300493,
 20300495,
 20300498,
 22201048,
 20300505,
 22201050,
 21200957,
 22201058,
 20300516,
 22201061,
 20300519,
 20800239,
 20800240,
 20300529,
 20800244,
 20300532,
 20800247,
 20300535,
 20800250,
 20800251,
 20800252,
 22201085,
 40600315,
 20800258,
 20800259,
 20300548,
 20300551,
 20800264,
 52200201,
 22201098,
 22201099,
 20800265,
 20800266,
 20800269,
 22201104,
 22201105,
 52200211,
 22201107,
 20300563,
 20300571,
 20800284,
 20300574,
 20800289,
 20800290,
 22201124,
 21300005,
 20800292,
 21300007,
 20800293,
 20800296,
 21300010,
 20300584,
 20800302,
 22201137,
 22201138,
 20800305,
 20800306,
 22201141,
 20800308,
 20701084,
 20701115,
 20300603,
 20300604,
 22201149,
 20800319,
 21300035,
 41100104,
 21200961,
 20300616,
 20300619,
 22201168,
 49800017,
 21300050,
 49800018,
 20800342,
 49800022,
 49800025,
 20800346,
 41100123,
 41100124,
 20800349,
 20300637,
 49800031,
 20800352,
 21300065,
 20300640,
 20300649,
 20300651,
 21300076,
 49800043,
 41100142,
 49800047,
 20800371,
 21300084,
 20800372,
 49800056,
 22201214,
 20800383,
 22201217,
 22201218,
 21300097,
 20300676,
 20800390,
 41100167,
 49800072,
 22201225,
 20800395,
 49800076,
 21300111,
 41100177,
 20300696,
 21300121,
 20800411,
 20300701,
 20300707,
 21300133,
 20300711,
 20800424,
 20300712,
 41100205,
 41100206,
 21300144,
 41100212,
 21300149,
 20300726,
 21300152,
 20300734,
 20800452,
 20300741,
 20300742,
 20300747,
 20800463,
 20800466,
 20300762,
 21300188,
 20300772,
 21300197,
 21300200,
 20800490,
 21300204,
 20300784,
 20300785,
 20300787,
 20800500,
 20800502,
 21200968,
 21300221,
 20800513,
 20800515,
 21300228,
 20300803,
 41100304,
 41100305,
 21200969,
 20300816,
 41100311,
 20300828,
 20800542,
 20800546,
 40100101,
 21300262,
 40100102,
 20300840,
 40100103,
 21300270,
 21300271,
 20300846,
 40100104,
 21300274,
 20800565,
 40100105,
 20800569,
 20800572,
 20800578,
 20300867,
 21800005,
 21300293,
 20300871,
 21800009,
 20300873,
 20300874,
 20300876,
 21300301,
 20800590,
 40100111,
 21300310,
 20800601,
 40100112,
 21300318,
 20800607,
 40100113,
 20800609,
 40100114,
 20300902,
 40100115,
 21800043,
 21800045,
 41100403,
 41100405,
 20800634,
 41600126,
 20800645,
 20800646,
 21300359,
 20800647,
 21800073,
 40100121,
 20300939,
 40100122,
 21800077,
 20300942,
 20300944,
 40100123,
 40100124,
 21800086,
 20800663,
 21800089,
 21300377,
 20800665,
 40100125,
 20300957,
 21300383,
 21800096,
 21800099,
 21800100,
 41600164,
 20800678,
 21800104,
 20800680,
 41600175,
 20800688,
 21800115,
 20300980,
 21300408,
 40100131,
 40100132,
 20800704,
 40100133,
 20800708,
 21300421,
 40100134,
 41600201,
 21800138,
 21800139,
 21300428,
 20301003,
 41600206,
 20800718,
 21300432,
 20800719,
 20301007,
 20301009,
 21300443,
 20800731,
 21800158,
 20701132,
 20800739,
 21300452,
 20800741,
 21800166,
 20301034,
 21800171,
 40100141,
 21300461,
 20301037,
 20301038,
 40100142,
 21300465,
 21100401,
 20800757,
 40100143,
 20301047,
 40100144,
 20800764,
 20800765,
 20301052,
 21300490,
 20301067,
 20301074,
 21300500,
 20301078,
 21300503,
 20301080,
 21800220,
 21300509,
 20800798,
 40100151,
 21300512,
 21300514,
 20800802,
 20800804,
 40100152,
 21800231,
 40100153,
 21800236,
 40100154,
 20301104,
 40100155,
 20301111,
 21300536,
 21800267,
 20301132,
 21300557,
 40100161,
 20800849,
 21300563,
 21300565,
 21200982,
 40100162,
 21300568,
 20800856,
 40100163,
 20800860,
 20701137,
 20800867,
 21800293,
 21300581,
 21800295,
 20301165,
 21300590,
 20301167,
 20301168,
 21300598,
 21800313,
 21300604,
 20301181,
 20800896,
 20301185,
 40100171,
 21300611,
 20800900,
 20301187,
 20800902,
 40100172,
 20800904,
 42100105,
 20800906,
 21300619,
 40100173,
 21300623,
 20800913,
 21800339,
 21800340,
 21300627,
 20800918,
 20800919,
 20700488,
 20800924,
 21300637,
 20800925,
 20800928,
 21300641,
 20800931,
 21800358,
 20800935,
 42100136,
 21300652,
 21300658,
 21300659,
 20800946,
 21800376,
 21800379,
 20800959,
 20701141,
 21800391,
 21800393,
 20800973,
 20800974,
 21800400,
 21300691,
 21800408,
 21300699,
 20800992,
 21800419,
 21300711,
 21300712,
 21300715,
 20801003,
 21800437,
 20801020,
 21300733,
 42100224,
 21800448,
 21300739,
 20801028,
 21200989,
 21300742,
 20801031,
 21100043,
 42100233,
 20801033,
 20801035,
 21800466,
 20801045,
 21300766,
 21800480,
 21300769,
 20801064,
 20801067,
 20801068,
 21300781,
 21300787,
 20801076,
 20801094,
 20801105,
 20801106,
 42100307,
 20801107,
 20801108,
 21800540,
 21300829,
 20801117,
 20801122,
 21800547,
 20801136,
 20801137,
 21800562,
 21300850,
 21800564,
 20801138,
 21300854,
 20801141,
 20801142,
 21300858,
 21300861,
 21800578,
 21300870,
 21200994,
 20701149,
 20801161,
 20801163,
 21800597,
 20801174,
 21800601,
 20801177,
 21200995,
 21800609,
 21300898,
 21800615,
 21800616,
 21300905,
 20801195,
 21800624,
 21300913,
 21300918,
 20801206,
 21300920,
 21300921,
 21800642,
 20801224,
 21300940,
 21800654,
 20801230,
 21800656,
 21300948,
 21300952,
 21300957,
 21800676,
 21200998,
 21200347,
 21800687,
 21800693,
 21800700,
 ...}

In [26]:
game_df = pd.read_csv('./raw_data/game.csv', sep=",")

In [29]:
team_stats = game_df[game_df['game_id'].isin(pbp_game_id_unique)]

In [74]:
game_df

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,...,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
0,21946,1610610035,HUS,Toronto Huskies,24600001,1946-11-01 00:00:00,HUS vs. NYK,L,0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,68.0,2,0,Regular Season
1,21946,1610610034,BOM,St. Louis Bombers,24600003,1946-11-02 00:00:00,BOM vs. PIT,W,0,20.0,...,NaN,NaN,NaN,NaN,NaN,25.0,51.0,-5,0,Regular Season
2,21946,1610610032,PRO,Providence Steamrollers,24600002,1946-11-02 00:00:00,PRO vs. BOS,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,53.0,-6,0,Regular Season
3,21946,1610610025,CHS,Chicago Stags,24600004,1946-11-02 00:00:00,CHS vs. NYK,W,0,21.0,...,NaN,NaN,NaN,NaN,NaN,22.0,47.0,-16,0,Regular Season
4,21946,1610610028,DEF,Detroit Falcons,24600005,1946-11-02 00:00:00,DEF vs. WAS,L,0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,50.0,17,0,Regular Season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65693,42022,1610612748,MIA,Miami Heat,42200403,2023-06-07 00:00:00,MIA vs. DEN,L,240,34.0,...,58.0,28.0,3.0,5.0,14.0,18.0,109.0,15,1,Playoffs
65694,42022,1610612748,MIA,Miami Heat,42200404,2023-06-09 00:00:00,MIA vs. DEN,L,240,35.0,...,34.0,26.0,11.0,7.0,8.0,18.0,108.0,13,1,Playoffs
65695,42022,1610612743,DEN,Denver Nuggets,42200405,2023-06-12 00:00:00,DEN vs. MIA,W,240,38.0,...,44.0,18.0,9.0,7.0,8.0,21.0,89.0,-5,1,Playoffs
65696,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19 00:00:00,LBN vs. GNS,L,221,79.0,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All-Star
65697,32022,1610616834,LBN,Team LeBron,32200001,2023-02-19 00:00:00,LBN vs. GNS,L,221,79.0,...,46.0,43.0,8.0,1.0,12.0,2.0,184.0,9,1,All Star

In [33]:
team_stats.to_csv('./raw_data/team_statistics.csv', index=False)

In [50]:
linescore_df = pd.read_csv('./raw_data/line_score.csv', sep=",")

In [51]:
linescore = linescore_df[linescore_df['game_id'].isin(pbp_game_id_unique)]

In [52]:
len(linescore)

25254

In [53]:
team_stats.to_csv('./raw_data/match_line_scores.csv', index=False)

game_date_est              object
game_sequence             float64
game_id                     int64
team_id_home                int64
team_abbreviation_home     object
team_city_name_home        object
team_nickname_home         object
team_wins_losses_home      object
pts_qtr1_home             float64
pts_qtr2_home             float64
pts_qtr3_home             float64
pts_qtr4_home             float64
pts_ot1_home              float64
pts_ot2_home              float64
pts_ot3_home              float64
pts_ot4_home              float64
pts_ot5_home              float64
pts_ot6_home              float64
pts_ot7_home              float64
pts_ot8_home              float64
pts_ot9_home              float64
pts_ot10_home             float64
pts_home                  float64
team_id_away                int64
team_abbreviation_away     object
team_city_name_away        object
team_nickname_away         object
team_wins_losses_away      object
pts_qtr1_away             float64
pts_qtr2_away             float64
pts_qtr3_away             float64
pts_qtr4_away             float64
pts_ot1_away              float64
pts_ot2_away              float64
pts_ot3_away              float64
pts_ot4_away              float64
pts_ot5_away              float64
pts_ot6_away              float64
pts_ot7_away              float64
pts_ot8_away              float64
pts_ot9_away              float64
pts_ot10_away             float64
pts_away                  float64
dtype: object

In [54]:
team_df = pd.read_csv('./raw_data/team_traditional.csv', sep=",")

In [59]:
team_df0 = team_df[team_df['gameid'].isin(pbp_game_id_unique)]

In [58]:
team_df

,gameid,date,type,teamid,team,home,away,MIN,PTS,FGM,...,DREB,REB,AST,TOV,STL,BLK,PF,+/-,win,season
0,29600001,1996-11-01,regular,1610612738,BOS,BOS,CHI,240.0,98.0,38.0,...,22.0,36.0,20.0,18.0,10.0,2.0,33.0,-45.0,0.0,1997
1,29600001,1996-11-01,regular,1610612741,CHI,BOS,CHI,240.0,107.0,42.0,...,29.0,37.0,28.0,19.0,7.0,8.0,23.0,45.0,1.0,1997
2,29600002,1996-11-01,regular,1610612739,CLE,NJN,CLE,238.0,90.0,34.0,...,23.0,35.0,16.0,15.0,11.0,1.0,24.0,65.0,1.0,1997
3,29600002,1996-11-01,regular,1610612751,NJN,NJN,CLE,241.0,77.0,23.0,...,24.0,35.0,13.0,21.0,7.0,7.0,19.0,-65.0,0.0,1997
4,29600003,1996-11-01,regular,1610612749,MIL,PHI,MIL,240.0,111.0,38.0,...,31.0,50.0,21.0,14.0,9.0,7.0,30.0,40.0,1.0,1997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65569,52200131,2023-04-12,playin,1610612740,NOP,NOP,OKC,48.0,118.0,42.0,...,34.0,48.0,27.0,11.0,5.0,4.0,23.0,-5.0,0.0,2023
65570,52200211,2023-04-14,playin,1610612750,MIN,MIN,OKC,48.0,120.0,43.0,...,38.0,47.0,29.0,17.0,11.0,8.0,15.0,25.0,1.0,2023
65571,52200201,2023-04-14,playin,1610612748,MIA,MIA,CHI,48.0,102.0,32.0,...,41.0,51.0,19.0,13.0,7.0,2.0,20.0,11.0,1.0,2023
65572,52200201,2023-04-14,playin,1610612741,CHI,MIA,CHI,48.0,91.0,36.0,...,32.0,37.0,24.0,11.0,5.0,3.0,25.0,-11.0,0.0,2023
65573,52200211,2023-04-14,playin,1610612760,OKC,MIN,OKC,48.0,95.0,32.0,...,30.0,42.0,19.0,18.0,9.0,6.0,20.0,-25.0,0.0,2023

In [60]:
len(team_df0['gameid'].unique())

28021

In [61]:
team_df0.to_csv('./raw_data/teamstats_traditional.csv', index=False)

In [68]:
boxscore = pd.read_csv('./raw_data/traditional.csv', sep=",")

In [69]:
boxscore0 = boxscore[boxscore['gameid'].isin(pbp_game_id_unique)]

In [70]:
len(boxscore0['gameid'].unique())

28021

In [71]:
len(boxscore0)

578283

In [72]:
boxscore0.to_csv('./raw_data/player_statistics.csv', index=False)

In [73]:
boxscore0

,gameid,date,type,playerid,player,team,home,away,MIN,PTS,...,DREB,REB,AST,STL,BLK,TOV,PF,+/-,win,season
0,29600001,1996-11-01,regular,893,Michael Jordan,CHI,BOS,CHI,43,30,...,3,4,3,0,0,1,2,11,1,1997
1,29600001,1996-11-01,regular,937,Scottie Pippen,CHI,BOS,CHI,40,18,...,7,8,6,2,0,5,4,28,1,1997
2,29600001,1996-11-01,regular,677,Eric Williams,BOS,BOS,CHI,25,14,...,1,3,1,0,0,1,4,1,0,1997
3,29600001,1996-11-01,regular,146,Jud Buechler,CHI,BOS,CHI,1,0,...,0,0,0,0,0,0,0,-2,1,1997
4,29600001,1996-11-01,regular,166,Ron Harper,CHI,BOS,CHI,25,7,...,1,2,5,2,1,0,1,15,1,1997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702363,42200404,2023-06-09,playoff,201145,Jeff Green,DEN,MIA,DEN,16,3,...,0,0,0,1,0,1,1,-7,1,2023
702364,42200404,2023-06-09,playoff,1629312,Haywood Highsmith,MIA,MIA,DEN,0,0,...,0,0,0,0,0,0,0,0,0,2023
702365,42200404,2023-06-09,playoff,1627750,Jamal Murray,DEN,MIA,DEN,43,15,...,3,3,12,1,0,0,1,22,1,2023
702366,42200404,2023-06-09,playoff,1628971,Bruce Brown,DEN,MIA,DEN,30,21,...,4,4,2,1,1,0,1,0,1,2023
702367,42200404,2023-06-09,playoff,1629622,Max Strus,MIA,MIA,DEN,19,0,...,4,5,0,0,0,0,3,-7,0,2023